### ISSUE TITLE
acf_form image uploader

### ISSUE THREAD

**Issue by hirasso** [elliotcondon/acf#461]
Hi there,

We are trying to use `acf_form()` for a submission form in the front-end of our website. We would like to use the built-in wordpress uploader, so that users don't have to select every single file separately. But users should still not be able to browse the media library. 

Is there a way to disable the media library for the image uploader in the front end?

**Comment by elliotcondon** [comment]
Hi @hirasso 

The closest you can get to this is to edit the image field and set the 'library' setting to 'uploaded to post'.
When creating a new post using acf_form and the post_id setting is not numeric, the media library will show any image which is not attached to a post.

If you set the post_id setting to 99999999999999 which is most likely not a post, the media library will show blank because no images are uploaded to this post.

You will need to use this as the post_id condition when creating a post if using the acf/pre_save_post filter.

If you have any further q's, please contact our support team here: http://support.advancedcustomfields.com/new-ticket/

**Comment by hirasso** [comment]
Hi @elliotcondon,
thank you for your hint. We will try this.
