### ISSUE TITLE
Allow URL Field to Accept mailto:

### ISSUE THREAD

**Issue by buschschwick** [elliotcondon/acf#480]
Hello!

I often use repeaters to allow users to add as many social media accounts that they want on the fly. The URL field is great for this, until they want to add an email option. Since `mailto:` is a valid URI, it would be nice if the ACF URL Field accepted it as an option. 

Any thoughts?

**Comment by elliotcondon** [comment]
Hi @buschschwick 

Thanks for the topic.

The issue is that the 'URL' field is an HTML5 input type="url" input.

The validation performed on this input is done by the browser, and the browser does not see mailto: as a valid URL (please correct me if I am wrong).

I am not able to override the HTML validation at this point in time and recommend that you use a text input for now.

Let me know if you have any ideas, or have found any solutions for this

Thanks
E

**Comment by buschschwick** [comment]
@elliotcondon yup, that makes sense! 

I've tried to stray away from using text fields in this instance to avoid client side errors when inputting URL's, etc. Thanks!
