### ISSUE TITLE
Featured Image with acf_form()

### ISSUE THREAD

**Issue by 3runoDesign** [elliotcondon/acf#602]
Is there any way to get the **featured image** with `acf_form()`?

**Comment by elliotcondon** [comment]
Hi @3runoDesign 

Thanks for the question.
The post featured image is not part of the acf_form() function, however, this could be easily achieved by creating an image field to handle the attachemnt selection.

You could then hook into the 'acf/update_value/name=featured_image' filter and save the selected image as the post's featured image.

You could also take this one step further and return `null` in that same filter so that ACF does not save anything to the field. You could also hook into the 'acf/update_value/name=featured_image' filter and load in the post's featured thumbnail so it could be edited

Good luck

**Comment by tristanleboss** [comment]
@elliotcondon It would be even simpler if acf_form could support featured image 👍 

Your solution does work but it's far from perfect/beautiful. Indeed, I had to add a group of fields with a mandatory image field to set the featured image. Because this field was mandatory, I had to create it using acf_add_local_field_group so it doesn't appear in WP backoffice (I don't want my user to have to set the featured image both in the WP metabox and my new group fields).

To be fair, it would be even better if acf_form was upgraded to support most (if not all) the WP fields available in the back office.

Instead of the post_title and post_content options, we can imagine a post_features option: an array where you specify what you want: post_title, post_content, post_featured_image, post_date

This could allow for amazing possibilities on the front end side.

**Comment by askwpgirl** [comment]
This is exactly why I have used Formidable Forms for all my front-facing add/update post forms because it integrates with ACF, taxonomies, featured image, etc. The Featured Image is itself a meta field, so it doesn't see that far fetched to map an ACF image field to the _thumbnail_id meta field. However, Formidable doesn't work with complex ACF fields like Repeater fields, so acf_form is more straight forward and ideal. As long as we have acf_form, we may was well take it all the way.
