### ISSUE TITLE
 Warning: Illegal string offset 'field_group' in advanced-custom-fields/core/fields/_functions.php on line 374

### ISSUE THREAD

**Issue by gonyot** [elliotcondon/acf#658]
Hi, i encounter this warning after i installed Advanced Custom field plugin in getshifter.io. I dont know how to fix this. can someone give advise or help me on how to solve this? With this warning, all the content of the field_control are blank and cant edit anything. here's the screenshot. https://gyazo.com/9e676d591b3efe117d18b3bd0bdf0d29

**Comment by elliotcondon** [comment]
Hi @gonyot 

This error suggests you have potentially corrupt field settings saved in your DB and ACF is having trouble unserializing the data (converting a string back into an array).

I am not aware of any other installations finding this issue, so it would be safe to say the issue is specific to your website / data. Please setup a fresh WP site and test out ACF. Test if you can replicate the issue with a fresh site/DB.

Next, try export / import your field groups across and test the issue again.

Please note this github repo is not for support. Please be sure to contact support here in the future: https://support.advancedcustomfields.com/new-ticket/

**Comment by gonyot** [comment]
@elliotcondon 

Thank you and sorry for posting on a wrong section. I will do as you've suggested. Thanks
