### ISSUE TITLE
ACF Pro 5.7.13: acf is not defined

### ISSUE THREAD

**Issue by Progressed36** [elliotcondon/acf#765]
Im using ACF Pro (latest version) on my front end of the website and get this error.

WP version: 5.1.1

Uncaught ReferenceError: acf is not defined
    at HTMLDocument.<anonymous> ((index):348)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

**Comment by elliotcondon** [comment]
Hi @Progressed36 

It sounds like something on the front-end of your site is trying to use the `acf` JS object. I suggest that you investigate what code is being run on line 348 of your page source (matching the error line number in your console log).

If you are using the `acf_form()` function, please be sure to use the `acf_form_head()` function so that ACF scripts can be enqueued.

if you are using a plugin that makes all scripts asynchronous or moves them to the footer, this may also explain why the acf JS object does not exist during hte page load.

**Comment by Progressed36** [comment]
Im completly sorry. It was another plugin that caused this error. Im using a plugin to use ACF on single products.

**Comment by elliotcondon** [comment]
Thanks for the reply, glad to hear things are working!
