### ISSUE TITLE
Data magically disappearing between environments. 

### ISSUE THREAD

**Issue by gbwashleybrown** [elliotcondon/acf#774]
Had a quick search, couldn't find another issue with my problem.

We have 3 environments - local - staging - production.

We have two branches in Github - staging/local & production.

We have 3 databases - local - staging - production

For some reason, after cloning the staging database and putting importing it into my local database, field data is showing up as blank - both in the WP admin and the frontend. The databases are 100% clones except for the site URL's in wp-options table.

If I look for a certain field that is blank inside the local database, I can see it. Just like how I can see it in the staging database.. same value, same key, same everything.

Yet when I go into the wp admin -> edit page or look  at a page that uses get_field(), there is no value... it is blank. 

If I look in the exact same place on our staging site, the data is intact as I'd expect. 

Note that the databases are exact copies of each other, so ID's are all identical between environments. The physical code is 100% identical between environments...

Anyone else had this issue or could advise me on how to fix this?

**Comment by elliotcondon** [comment]
Hi @gbwashleybrown 

I suspect there must be something custom conflicting with the loading of data. If the files are the same, and the database is the same, there should be no reason why you are seeing different results across websites.

You mention that the DB meta table does contain the value, yet it doesn't appear in the wp-admin. This is very strange indeed, and points towards some kind of conflict.

Could this be a caching issue?

To fix this issue, I advise that you get to work debugging the PHP code within ACF and WP core that handles loading meta. This will be the fastest way to figure out what is going wrong :)

P.S. This repository is not the place for this kind of support. If you find a specific code related bug, please do report it here. Otherwise, please get in touch with our support team over at https://www.advancedcustomfields.com/contact/

**Comment by gbwashleybrown** [comment]
@elliotcondon Hi Elliot, 

Thank you for the advice and response.

I did send an email but I had no response and it was kind of time critical. I did eventually find the issue and it was a slight mismatch between MySQL engines between environments - we overlooked this and only focused on the data aspect.
